services:
  seaqa-events:
    image: ${SEATICKET_EVENTS_IMAGE:-docker.seafile.top/seafileltd/seaqa-events:0.2.0-testing}
    restart: unless-stopped
    container_name: seaqa-events
    volumes:
      - /opt/seaticket/seaticket-data/conf:/opt/seaticket/conf
      - ${SEATICKET_VOLUME:-/opt/seaticket/seaticket-data}:/shared
    environment:
      - LOG_TO_STDOUT=${LOG_TO_STDOUT:-false}
      - TZ=${TIME_ZONE:-UTC}
      - JWT_PRIVATE_KEY=${JWT_PRIVATE_KEY:?Variable is not set or empty}
      - SEADB_SERVER_URL=${SEADB_SERVER_URL:-seadb}
      - SEADB_SERVER_ACCESS_TOKEN=${SEADB_SERVER_ACCESS_TOKEN:?Variable is not set or empty}
      - MYSQL_DB_HOST=${MYSQL_DB_HOST:?Variable is not set or empty}
      - MYSQL_DB_PORT=${MYSQL_DB_PORT:-3306}
      - MYSQL_DB_USER=${MYSQL_DB_USER:-seaticket}
      - MYSQL_DB_PASSWORD=${MYSQL_DB_PASSWORD:-}
      - MYSQL_DB_NAME=${MYSQL_DB_NAME:-seaticket_db}
      - REDIS_HOST=${REDIS_HOST:?Variable is not set or empty}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
    networks:
      - backend-net
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f seaqa_events.main || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  backend-net:
    name: backend-net
